### ISSUE TITLE
Please split URLs in base url and file name using variables

### ISSUE THREAD

**Issue by draeger** [hemilpanchiwala/SBSCL#2]
https://github.com/hemilpanchiwala/SBSCL/blob/97ee6c54d82c656ab39835ee39442ebe3480a4b0/src/test/download_sbml-test-suite.sh#L14

Please use the base variable for the URL and one for the file name so that the file name has to be written in the script only once and to allow easy update of the base URL.

**Comment by hemilpanchiwala** [comment]
@draeger, we should close this issue as it's updated in the testrunner branch.
