### ISSUE TITLE
Refactor SBMLTestSuiteRunnerWrapper

### ISSUE THREAD

**Issue by draeger** [hemilpanchiwala/SBSCL#3]
The class `SBMLTestSuiteRunnerWrapper` has one relatively complex `main` method that performs many different tasks. Better would be if the main method could first create a new instance of `SBMLTestSuiteRunnerWrapper` and then call different methods of it to go through the process step by step.

**Comment by hemilpanchiwala** [comment]
@draeger, This is now done in PR [#54](https://github.com/draeger-lab/SBSCL/pull/54). So, we can close this issue now.
