### ISSUE TITLE
Rename COBRASolver to FBA

### ISSUE THREAD

**Issue by draeger** [hemilpanchiwala/SBSCL#4]
The class `COBRASolver` is essentially an implementation of a method called Flux Balance Analysis (FBA) and should therefore be renamed. Please indicate this in the release notes for upcoming versions. In the future, many different COBRA methods should be added, so that this name is no longer suitable.

**Comment by draeger** [comment]
It would probably be better to rename it to `FluxBalanceAnalysis` to give it a more descriptive name.

**Comment by hemilpanchiwala** [comment]
@draeger, refactored CobraSolver to FluxBalanceAnalysis in the commit linked above!
