### ISSUE TITLE
Fix equality constraints also for FBC version 1

### ISSUE THREAD

**Issue by draeger** [hemilpanchiwala/SBSCL#5]
SCPSolver does not accept upper bounds to be identical to lower bounds. For FBC version 2 models this is being taken care of, but not for version 1. Please turn the small check and fix into a method call and apply it in both situations.

**Comment by hemilpanchiwala** [comment]
@draeger, this issue is solved in the above-linked commit. Please review once.

**Comment by hemilpanchiwala** [comment]
@draeger, we can close this as it is merged in the main SBSCL repository.
